%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/demasma/Box Sync/Nasa Flight Data/DataAnalysis_Matt/NASA-PEC-R-Analysis/Data/hp_demo_physio_trial_v4_2016-03-04.xlsx
%    Worksheet: hp_demo_physio_trial_v2_2016-03
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/03/04 13:32:01

%% Import the data
[~, ~, raw] = xlsread('/Users/matt/Box Sync/Nasa Flight Data/DataAnalysis_Matt/NASA-PEC-R-Analysis/Data/hp_demo_physio_trial_v4_2016-03-04.xlsx','hp_demo_physio_trial_v2_2016-03');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6,7,8,9,12,13]);
raw = raw(:,[10,11,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
pec_data = table;

%% Allocate imported array to column variable names
pec_data.Subject = cellVectors(:,1);
pec_data.Run = cellVectors(:,2);
pec_data.Protocol = cellVectors(:,3);
pec_data.Sessionid = cellVectors(:,4);
pec_data.Runid = cellVectors(:,5);
pec_data.Task = cellVectors(:,6);
pec_data.Trial = cellVectors(:,7);
pec_data.Trialid = cellVectors(:,8);
pec_data.Session = cellVectors(:,9);
pec_data.SubjectTrial = data(:,1);
pec_data.PRQ = data(:,2);
pec_data.SessionOrder = cellVectors(:,10);
pec_data.RunOrder = cellVectors(:,11);
pec_data.CFT_TotalCombined = data(:,3);
pec_data.CFT_TotalCompleteScore = data(:,4);
pec_data.CFT_TotalCorrectScore = data(:,5);
pec_data.COG_DASCPUT = data(:,6);
pec_data.COG_DASCRTC = data(:,7);
pec_data.COG_DATDRTC = data(:,8);
pec_data.COG_DATIRTC = data(:,9);
pec_data.COG_DATSCAC = data(:,10);
pec_data.COG_MTSACC = data(:,11);
pec_data.COG_MTSPUT = data(:,12);
pec_data.COG_MTSRTC = data(:,13);
pec_data.COG_PFCACC = data(:,14);
pec_data.COG_PFCPUT = data(:,15);
pec_data.COG_PFCRTC = data(:,16);
pec_data.COG_SDCACC = data(:,17);
pec_data.COG_SDCPUT = data(:,18);
pec_data.COG_SDCRTC = data(:,19);
pec_data.COG_VSCACC = data(:,20);
pec_data.COG_VSCPUT = data(:,21);
pec_data.COG_VSCRTC = data(:,22);
pec_data.MATB_Comm = data(:,23);
pec_data.MATB_Overall = data(:,24);
pec_data.MATB_ResMgmt = data(:,25);
pec_data.MATB_Tracking = data(:,26);
pec_data.SIM_Altitude = data(:,27);
pec_data.SIM_Heading = data(:,28);
pec_data.SIM_Speed = data(:,29);
pec_data.tlx_score = data(:,30);
pec_data.scale_mental = data(:,31);
pec_data.scale_physical = data(:,32);
pec_data.scale_temporal = data(:,33);
pec_data.scale_perform = data(:,34);
pec_data.scale_effort = data(:,35);
pec_data.scale_frustration = data(:,36);
pec_data.Age = data(:,37);
pec_data.Gender = data(:,38);
pec_data.Height = data(:,39);
pec_data.Weight = data(:,40);
pec_data.TotalFlightHours = data(:,41);
pec_data.SixMonthsFlightHr = data(:,42);
pec_data.YearsFlying = data(:,43);
pec_data.MedicalCertClass = data(:,44);
pec_data.DailyComputerHrs = data(:,45);
pec_data.ComputerGamesDaysPerMonth = data(:,46);
pec_data.ComputerGameHours = data(:,47);
pec_data.PercentFlightSim = data(:,48);
pec_data.X39 = data(:,49);
pec_data.X40 = data(:,50);
pec_data.X38 = data(:,51);
pec_data.X1 = data(:,52);
pec_data.X2 = data(:,53);
pec_data.X3 = data(:,54);
pec_data.X4 = data(:,55);
pec_data.X5 = data(:,56);
pec_data.X6 = data(:,57);
pec_data.X7 = data(:,58);
pec_data.X8 = data(:,59);
pec_data.X9 = data(:,60);
pec_data.X10 = data(:,61);
pec_data.X11 = data(:,62);
pec_data.X12 = data(:,63);
pec_data.X13 = data(:,64);
pec_data.X14 = data(:,65);
pec_data.X15 = data(:,66);
pec_data.X16 = data(:,67);
pec_data.X17 = data(:,68);
pec_data.X18 = data(:,69);
pec_data.X20 = data(:,70);
pec_data.X21 = data(:,71);
pec_data.X22 = data(:,72);
pec_data.X23 = data(:,73);
pec_data.X24 = data(:,74);
pec_data.X25 = data(:,75);
pec_data.X26 = data(:,76);
pec_data.X27 = data(:,77);
pec_data.X28 = data(:,78);
pec_data.X30 = data(:,79);
pec_data.X31 = data(:,80);
pec_data.X32 = data(:,81);
pec_data.X33 = data(:,82);
pec_data.X34 = data(:,83);
pec_data.X35 = data(:,84);
pec_data.X36 = data(:,85);
pec_data.X37 = data(:,86);
pec_data.X41 = data(:,87);
pec_data.X42 = data(:,88);
pec_data.PartNumber = data(:,89);
pec_data.ProtocolNumber = data(:,90);
pec_data.Study = data(:,91);
pec_data.TypeofRun = data(:,92);
pec_data.ParticipantNumber = data(:,93);
pec_data.TypeOfRun = data(:,94);

%% Clear temporary variables
clearvars data raw cellVectors R;