%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/demasma/Box Sync/Nasa Flight Data/DataAnalysis_Matt/NASA-PEC-R-Analysis/Data/hp_data_demo_NA-to-minus-1000_v3_2016-03-03.xlsx
%    Worksheet: hp_data_demo_v2_2016-03-03.csv
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/03/03 20:15:17

%% Import the data
[~, ~, raw] = xlsread('/Users/demasma/Box Sync/Nasa Flight Data/DataAnalysis_Matt/NASA-PEC-R-Analysis/Data/hp_data_demo_NA-to-minus-1000_v3_2016-03-03.xlsx','hp_data_demo_v2_2016-03-03.csv');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,3,4,5,6,7,8,9,10,13,14,50,56]);
raw = raw(:,[1,11,12,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,51,52,53,54,55,57,58,59,60]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
hp_data = table;

%% Allocate imported array to column variable names
hp_data.VarName1 = data(:,1);
hp_data.Subject = cellVectors(:,1);
hp_data.Run = cellVectors(:,2);
hp_data.Protocol = cellVectors(:,3);
hp_data.Sessionid = cellVectors(:,4);
hp_data.Runid = cellVectors(:,5);
hp_data.Task = cellVectors(:,6);
hp_data.Trial = cellVectors(:,7);
hp_data.Trialid = cellVectors(:,8);
hp_data.Session = cellVectors(:,9);
hp_data.SubjectTrial = data(:,2);
hp_data.PRQ = data(:,3);
hp_data.SessionOrder = cellVectors(:,10);
hp_data.RunOrder = cellVectors(:,11);
hp_data.CFT_TotalCombined = data(:,4);
hp_data.CFT_TotalCompleteScore = data(:,5);
hp_data.CFT_TotalCorrectScore = data(:,6);
hp_data.COG_DASCPUT = data(:,7);
hp_data.COG_DASCRTC = data(:,8);
hp_data.COG_DATDRTC = data(:,9);
hp_data.COG_DATIRTC = data(:,10);
hp_data.COG_DATSCAC = data(:,11);
hp_data.COG_MTSACC = data(:,12);
hp_data.COG_MTSPUT = data(:,13);
hp_data.COG_MTSRTC = data(:,14);
hp_data.COG_PFCACC = data(:,15);
hp_data.COG_PFCPUT = data(:,16);
hp_data.COG_PFCRTC = data(:,17);
hp_data.COG_SDCACC = data(:,18);
hp_data.COG_SDCPUT = data(:,19);
hp_data.COG_SDCRTC = data(:,20);
hp_data.COG_VSCACC = data(:,21);
hp_data.COG_VSCPUT = data(:,22);
hp_data.COG_VSCRTC = data(:,23);
hp_data.MATB_Comm = data(:,24);
hp_data.MATB_Overall = data(:,25);
hp_data.MATB_ResMgmt = data(:,26);
hp_data.MATB_Tracking = data(:,27);
hp_data.SIM_Altitude = data(:,28);
hp_data.SIM_Heading = data(:,29);
hp_data.SIM_Speed = data(:,30);
hp_data.tlx_score = data(:,31);
hp_data.scale_mental = data(:,32);
hp_data.scale_physical = data(:,33);
hp_data.scale_temporal = data(:,34);
hp_data.scale_perform = data(:,35);
hp_data.scale_effort = data(:,36);
hp_data.scale_frustration = data(:,37);
hp_data.Age = data(:,38);
hp_data.Gender = cellVectors(:,12);
hp_data.Height = data(:,39);
hp_data.Weight = data(:,40);
hp_data.TotalFlightHours = data(:,41);
hp_data.SixMonthsFlightHr = data(:,42);
hp_data.YearsFlying = data(:,43);
hp_data.MedicalCertClass = cellVectors(:,13);
hp_data.DailyComputerHrs = data(:,44);
hp_data.ComputerGamesDaysPerMonth = data(:,45);
hp_data.ComputerGameHours = data(:,46);
hp_data.PercentFlightSim = data(:,47);

%% Clear temporary variables
clearvars data raw cellVectors;