%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/matt/Box Sync/Nasa Flight Data/PEC Study data/HumanPerformance/Sim Perf Raw Data/PEC_S53_PF_S3_R2_SIM2_20150811164727_casbaro.xlsm
%    Worksheet: PEC_S53_PF_S3_R2_SIM2_201508111
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/03/14 16:18:41

%% Import the data
[~, ~, raw] = xlsread('/Users/matt/Box Sync/Nasa Flight Data/PEC Study data/HumanPerformance/Sim Perf Raw Data/PEC_S53_PF_S3_R2_SIM2_20150811164727_casbaro.xlsm','PEC_S53_PF_S3_R2_SIM2_201508111');
raw = raw(2:end,[1:4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,47,48]);
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
s57sim2_tab = table;

%% Allocate imported array to column variable names
s57sim2_tab.Subject_Number = cellVectors(:,1);
s57sim2_tab.time = data(:,1);
s57sim2_tab.dp_time = data(:,2);
s57sim2_tab.Speed = data(:,3);
s57sim2_tab.Pos_NED_X = data(:,4);
s57sim2_tab.Pos_NED_Y = data(:,5);
s57sim2_tab.Lat = data(:,6);
s57sim2_tab.Long = data(:,7);
s57sim2_tab.AltPos_WGS84_Z = data(:,8);
s57sim2_tab.Bank_Anglephi = data(:,9);
s57sim2_tab.pitch_angletheta = data(:,10);
s57sim2_tab.HeadingMagPsi = data(:,11);
s57sim2_tab.headingpsi = data(:,12);
s57sim2_tab.xDot = data(:,13);
s57sim2_tab.yDot = data(:,14);
s57sim2_tab.zDot = data(:,15);
s57sim2_tab.phiDot = data(:,16);
s57sim2_tab.thetaDot = data(:,17);
s57sim2_tab.psiDot = data(:,18);
s57sim2_tab.normal_acceleration = data(:,19);
s57sim2_tab.Headingexp_state = data(:,20);
s57sim2_tab.Altexp_state = data(:,21);
s57sim2_tab.Speedexp_state = data(:,22);
s57sim2_tab.Snippet_number = data(:,23);
s57sim2_tab.Stick1_PosX = data(:,24);
s57sim2_tab.Stick1_PosY = data(:,25);
s57sim2_tab.Stick1_ForceX = data(:,26);
s57sim2_tab.Stick1_ForceY = data(:,27);
s57sim2_tab.Stick2_PosX = data(:,28);
s57sim2_tab.Stick2_PosY = data(:,29);
s57sim2_tab.Stick2_ForceX = data(:,30);
s57sim2_tab.Stick2_ForceY = data(:,31);
s57sim2_tab.ROBD_program = data(:,32);
s57sim2_tab.ROBD_Alt = data(:,33);
s57sim2_tab.ROBD_final_Alt = data(:,34);
s57sim2_tab.ROBD_O2_conc = data(:,35);
s57sim2_tab.ROBD_BL_Press = data(:,36);
s57sim2_tab.ROBD_Elapsed_Time = data(:,37);
s57sim2_tab.ROBD_Remaining_Time = data(:,38);
s57sim2_tab.ROBD_SPO2 = data(:,39);
s57sim2_tab.ROBD_Pulse = data(:,40);
s57sim2_tab.GTEC_Time = data(:,41);
s57sim2_tab.GTEC_EKG = data(:,42);
s57sim2_tab.GTEC_Pulse = data(:,43);
s57sim2_tab.GTEC_O2_Sat = data(:,44);
s57sim2_tab.GTEC_Resperation = data(:,45);
s57sim2_tab.ROBD_Date = cellVectors(:,2);
s57sim2_tab.ROBD_Time = cellVectors(:,3);

%% Clear temporary variables
clearvars data raw cellVectors R;