%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/matt/Box Sync/Nasa Flight Data/PEC Study data/HumanPerformance/Sim Perf Raw Data/PEC_S53_PF_S3_R2_SIM2_20150811164727_casbaro.xlsm
%    Worksheet: PEC_S53_PF_S3_R2_SIM2_201508111
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/03/14 16:02:42

%% Import the data
[~, ~, raw] = xlsread('/Users/matt/Box Sync/Nasa Flight Data/PEC Study data/HumanPerformance/Sim Perf Raw Data/PEC_S53_PF_S3_R2_SIM2_20150811164727_casbaro.xlsm','PEC_S53_PF_S3_R2_SIM2_201508111');
raw = raw(2:end,[2:4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
s57sim2 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;